package:
  name: wxpython
  version: 3.0.2.0

source:
  fn: wxPython-src-3.0.2.0.tar.bz2
  url: http://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2

build:
  number: 0

  script: $RECIPE_DIR/build_osx.sh #[osx]
  script: $RECIPE_DIR/build.sh #[linux]
  skip: True  #[win]
  skip: True  #[linux]
  skip: True  #[osx] # until I get the build errors figured out


requirements:
  build:
    - python >=2.7,<3
    - setuptools

  run:
    - python

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: 'Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
