# Note: this recipe simply downloads and installs the binary wheels built by the project.
#       This means it used statically linked versions of libs that it could get from conda

# There are curretnly only development snapshots available
{% set version = "3.0.3.dev2832" %}

package:
  name: wxpython-phoenix
  version:  {{ version }}

build:
  number: 0
  script: pip install -U --pre --trusted-host wxpython.org -f http://wxpython.org/Phoenix/snapshot-builds wxPython_Phoenix # [osx or win32 or win64]

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
    - libxml2
    - libiconv # [linux64]
    - libgcc >=5.1 # [linux64]
    - pango >=1.40 # [linux64]

  run:
    - python
    - six
    - requests
    - six
    - libxml2
    - libiconv # [linux64]
    - libgcc >=5.1 # [linux64]
    - pango >=1.40 # [linux64]

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: '*new* Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
