# Note: this recipe simply downloads and installs the binary wheels built by the project.
#       This means it used statically linked versions of libs that it could get from conda

# There are curretnly only development snapshots available
{% set version = "3.0.3.dev2832" %}

package:
  name: wxpython-phoenix
  version:  {{ version }}

build:
  number: 1
  script: pip install -U --pre --trusted-host wxpython.org -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix=={{ version }} # [osx or win32 or win64]
  script: pip install -U --pre --trusted-host wxpython.org -f http://wxpython.org/Phoenix/snapshot-builds/linux/gtk2/fedora-24 wxPython_Phoenix=={{ version }} # [linux64]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: '*new* Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
