# Note: this recipe simply downloads and installs the binary wheels built by the project.

package:
  name: wxpython-phoenix
  version: 4.0

build:
  number: 0
  script: pip install -U wxPython # [win32 or win64]

requirements:
  build:
    - python
    - setuptools
    - requests
    - six >=0.10.0
    - libxml2 # [osx or linux64]
    - libiconv # [linux64]
    - libgcc >=5.1 # [linux64]
    - pango >=1.40 # [linux64]

  run:
    - python
    - six
    - requests
    - six >=0.10.0
    - libxml2 # [osx or linux64]
    - libiconv # [linux64]
    - libgcc >=5.1 # [linux64]
    - pango >=1.40 # [linux64]

# test:
#    imports:
#        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: '*new* Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
